version: '0.1.{build}'
configuration:
- Debug
- Release
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
pull_requests:  
  do_not_increment_build_number: true
branches:  
  only:
  - master
nuget:  
  disable_publish_on_pr: true
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build "Transdirect" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
after_build:
- dotnet pack "Transdirect" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
test: off  
artifacts:  
- path: .\artifacts\**\*.nupkg
  name: NuGet
deploy:  
- provider: NuGet
  server: https://www.myget.org/F/nkahoang/api/v2/package
  api_key:
    secure: j3bSxNrCwqDekpgZEagnFCoWDKLX9X0T2emPEeSPwEdUGzgfSI1kFmwXXRnWmC9r
  skip_symbols: true
  on:
    branch: master
- provider: NuGet
  name: production
  api_key:
    secure: jIeZyZUNqaGQlNi/m9c6Ypjr/Hkc0xCpo1jzR1H46BRmxfEi+weW8cJOcBiIaOfZ
  on:
    branch: production
    appveyor_repo_tag: true
